"""Generate a paper scatter plot for surface similarity failures.

The figure uses cached outputs and row-level judgments only. It is meant to
support RQ2: high surface similarity is not sufficient evidence of either
privacy safety or task-critical utility.
"""

from __future__ import annotations

import argparse
from collections import Counter
from pathlib import Path
from types import SimpleNamespace

from analyze_surface_metrics import build_rows, median
from io_utils import write_json


CATEGORIES = [
    ("no_measured_failure", "No measured failure", "gray!55", "*", 0.45),
    ("utility_failure", "Utility failure", "orange!85!black", "square*", 0.65),
    ("privacy_failure", "Privacy failure", "red!75!black", "triangle*", 0.78),
]


def fmt(value: float) -> str:
    return f"{value:.3f}"


def category(row: dict) -> str:
    if row["privacy_failure"]:
        return "privacy_failure"
    if row["utility_failure"]:
        return "utility_failure"
    return "no_measured_failure"


def coords(rows: list[dict]) -> str:
    if not rows:
        return ""
    return " ".join(f"({fmt(row['tfidf_cosine'])},{fmt(row['audited_tcfr'])})" for row in rows)


def build_summary(rows: list[dict], source_label: str) -> dict:
    threshold = median([row["tfidf_cosine"] for row in rows])
    high = [row for row in rows if row["tfidf_cosine"] >= threshold]
    counts = Counter(category(row) for row in rows)
    high_counts = Counter(category(row) for row in high)
    by_method = {}
    for method in sorted({row["method"] for row in rows}):
        method_rows = [row for row in rows if row["method"] == method]
        by_method[method] = {
            "rows": len(method_rows),
            "privacy_failure_rows": sum(1 for row in method_rows if row["privacy_failure"]),
            "utility_failure_rows": sum(1 for row in method_rows if row["utility_failure"]),
            "audited_fact_loss_rows": sum(1 for row in method_rows if row["audited_fact_failure"]),
            "qa_failure_rows": sum(1 for row in method_rows if row["qa_failure"]),
            "mean_tfidf_cosine": sum(row["tfidf_cosine"] for row in method_rows) / len(method_rows),
            "mean_audited_tcfr": sum(row["audited_tcfr"] for row in method_rows) / len(method_rows),
        }
    return {
        "source": source_label,
        "rows": len(rows),
        "tfidf_median_threshold": threshold,
        "high_similarity_rows": len(high),
        "high_similarity_privacy_failure_rows": sum(1 for row in high if row["privacy_failure"]),
        "high_similarity_audited_fact_loss_rows": sum(1 for row in high if row["audited_fact_failure"]),
        "high_similarity_qa_failure_rows": sum(1 for row in high if row["qa_failure"]),
        "category_counts": dict(counts),
        "high_similarity_category_counts": dict(high_counts),
        "by_method": by_method,
    }


def write_tex(rows: list[dict], summary: dict, out_path: str, sample_label: str) -> None:
    by_category = {key: [row for row in rows if category(row) == key] for key, *_ in CATEGORIES}
    threshold = summary["tfidf_median_threshold"]
    lines = [
        "% Auto-generated by src/make_surface_failure_scatter.py; do not edit by hand.",
        r"\begin{figure}[t]",
        r"\centering",
        r"\begin{tikzpicture}",
        r"\begin{axis}[",
        r"  width=0.74\linewidth,",
        r"  height=4.25cm,",
        r"  xmin=0.18,",
        r"  xmax=1.01,",
        r"  ymin=0.00,",
        r"  ymax=1.04,",
        r"  xlabel={TF-IDF cosine to original text},",
        r"  ylabel={Audited \tcfr{}},",
        r"  grid=both,",
        r"  grid style={line width=.1pt, draw=gray!25},",
        r"  tick label style={font=\scriptsize},",
        r"  label style={font=\small},",
        r"  legend style={font=\scriptsize, draw=none, fill=none, at={(0.5,-0.30)}, anchor=north, legend columns=3},",
        r"  clip=false,",
        r"]",
    ]
    for key, label, color, mark, opacity in CATEGORIES:
        lines.append(
            rf"\addplot+[only marks, mark={mark}, mark size=1.25pt, color={color}, opacity={opacity}] "
            rf"coordinates {{{coords(by_category[key])}}};"
        )
        lines.append(rf"\addlegendentry{{{label}}}")
    lines.extend(
        [
            rf"\addplot+[dashed, thin, color=black!55, mark=none] coordinates {{({fmt(threshold)},0.00) ({fmt(threshold)},1.04)}};",
            rf"\node[font=\scriptsize, align=left, anchor=south west] at (axis cs:{fmt(threshold + 0.015)},0.06) {{median TF-IDF\\{fmt(threshold)}}};",
            r"\end{axis}",
            r"\end{tikzpicture}",
            (
                rf"\caption{{Surface similarity failure scatter for the {sample_label} non-oracle run. "
                rf"Among the {summary['high_similarity_rows']} rows at or above the median TF-IDF cosine, "
                rf"{summary['high_similarity_privacy_failure_rows']} still have privacy failures and "
                rf"{summary['high_similarity_audited_fact_loss_rows']} have audited fact loss.}}"
            ),
            r"\label{fig:surface-scatter}",
            r"\end{figure}",
            "",
        ]
    )
    out = Path(out_path)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--benchmark", default="data/processed/benchmark.jsonl")
    parser.add_argument("--outputs", default="data/processed/openai_anonymized_outputs_n100.jsonl")
    parser.add_argument("--scored", default="data/processed/openai_judgments_n100.jsonl")
    parser.add_argument("--fact-judgments", default="data/processed/openai_fact_judgments_n100.jsonl")
    parser.add_argument("--high-qi-threshold", type=float, default=2.0)
    parser.add_argument("--out-tex", default="paper/generated_surface_failure_scatter.tex")
    parser.add_argument("--out-json", default="results/surface_failure_scatter_n100.json")
    parser.add_argument("--sample-label", default="100-example")
    parser.add_argument("--source-label", default="cached surface audit inputs")
    args = parser.parse_args()

    rows = build_rows(SimpleNamespace(**vars(args)))
    summary = build_summary(rows, args.source_label)
    write_json(args.out_json, summary)
    write_tex(rows, summary, args.out_tex, args.sample_label)
    print(f"wrote {args.out_tex}")
    print(f"wrote {args.out_json}")


if __name__ == "__main__":
    main()
