"""Generate paper-ready LaTeX figures from current result summaries."""

from __future__ import annotations

import argparse
import json
from pathlib import Path


METHODS = [
    ("generic_llm", "Generic LLM", "blue!65!black", "*"),
    ("privacy_first_llm", "Privacy-first LLM", "orange!85!black", "square*"),
    ("critical_span_guard_extracted", "Critical Span Guard", "green!45!black", "triangle*"),
]


def load(path: str | Path) -> dict:
    with Path(path).open("r", encoding="utf-8") as f:
        return json.load(f)


def mean(summary: dict, method: str, key: str) -> float:
    value = summary["overall"][method][key]
    if isinstance(value, dict):
        return float(value["mean"])
    return float(value)


def fmt(value: float) -> str:
    return f"{value:.3f}"


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--det-summary", default="results/openai_summary.json")
    parser.add_argument("--audit-summary", default="results/openai_fact_judge_summary.json")
    parser.add_argument("--out", default="paper/generated_privacy_utility_frontier.tex")
    parser.add_argument("--sample-label", default="50-example")
    args = parser.parse_args()

    det = load(args.det_summary)
    audit = load(args.audit_summary)

    x_values = [mean(det, method, "quasi_identifier_risk") for method, _label, _color, _mark in METHODS]
    y_values = [float(audit["overall"][method]["audited_tcfr"]) for method, _label, _color, _mark in METHODS]
    xmax = max(1.9, max(x_values) + 0.15)
    ymin = max(0.0, min(y_values) - 0.08)

    lines = [
        "% Auto-generated by src/make_paper_figures.py; do not edit by hand.",
        r"\begin{figure}[t]",
        r"\centering",
        r"\begin{tikzpicture}",
        r"\begin{axis}[",
        r"  width=0.68\linewidth,",
        r"  height=4.3cm,",
        r"  xmin=0,",
        f"  xmax={xmax:.2f},",
        f"  ymin={ymin:.2f},",
        r"  ymax=1.03,",
        r"  xlabel={QI risk (lower is better)},",
        r"  ylabel={Audited \tcfr{} (higher is better)},",
        r"  grid=both,",
        r"  grid style={line width=.1pt, draw=gray!25},",
        r"  tick label style={font=\scriptsize},",
        r"  label style={font=\small},",
        r"  legend style={font=\scriptsize, draw=none, fill=none, at={(0.5,-0.32)}, anchor=north, legend columns=1},",
        r"  clip=false,",
        r"]",
    ]
    for method, label, color, mark in METHODS:
        qi = mean(det, method, "quasi_identifier_risk")
        audited = float(audit["overall"][method]["audited_tcfr"])
        lines.append(
            rf"\addplot+[only marks, mark={mark}, mark size=2.8pt, color={color}] coordinates {{({fmt(qi)},{fmt(audited)})}};"
        )
        lines.append(rf"\addlegendentry{{{label}}}")
    lines.extend(
        [
            r"\node[font=\scriptsize, align=center, anchor=west] at (axis cs:0.13,0.96) {lower risk\\higher utility};",
            r"\draw[->, gray!70] (axis cs:0.45,0.82) -- (axis cs:0.16,0.94);",
            r"\end{axis}",
            r"\end{tikzpicture}",
            rf"\caption{{Privacy--utility frontier for the {args.sample_label} non-oracle LLM run. \method{{}} is closest to the upper-left target region: lower measured quasi-identifier risk and higher audited task-critical fact retention.}}",
            r"\label{fig:frontier}",
            r"\end{figure}",
            "",
        ]
    )
    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {out}")


if __name__ == "__main__":
    main()
